name: Gettext updates
on:
  push:
    branches: master
jobs:
  gettext_template:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: elementary/actions/gettext-template@master
        env:
          GIT_USER_TOKEN: "${{ secrets.GIT_USER_TOKEN }}"
          GIT_USER_NAME: "avojak"
          GIT_USER_EMAIL: "andrew.vojak@gmail.com"
        with:
          translation_branch: "master"